#!/usr/bin/bash
#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# We grep a string of the default DH key, if true we create a DH key for the ejabberd service
#

if ! /usr/bin/grep -q 'MIIBCAKCAQEAuOOxlQk6szIFHw' /etc/ejabberd/dh2048.pem; then
    exit 0
fi
tmpfile=$(mktemp /tmp/ejabberd-create-dhparam.XXXXXXX)
trap "/usr/bin/rm -f ${tmpfile}" EXIT

set -e # Exit immediately if any error occurs

/usr/bin/openssl dhparam -out ${tmpfile} 2048
/usr/bin/mv -f ${tmpfile} /etc/ejabberd/dh2048.pem
/usr/bin/chown root:ejabberd /etc/ejabberd/dh2048.pem
/usr/bin/chmod 440 /etc/ejabberd/dh2048.pem
